insert into mart.d_calendar (date_actual, 
	epoch, 
	day_suffix, 
	day_name, 
	day_of_week, 
	day_of_month, 
	day_of_quarter, 
	day_of_year, 
	week_of_month, 
	week_of_year, 
	week_of_year_iso, 
	month_actual, 
	month_name, 
	month_name_abbreviated, 
	quarter_actual, 
	quarter_name, 
	year_actual, 
	first_day_of_week, 
	last_day_of_week, 
	first_day_of_month, 
	last_day_of_month, 
	first_day_of_quarter, 
	last_day_of_quarter, 
	first_day_of_year, 
	last_day_of_year, 
	mmyyyy, 
	mmddyyyy, 
	weekend_indr)
select 
	date::date date_actual,
	date_part('epoch', date) epoch,
	to_char(date, 'FMddth') day_suffix,
	to_char(date, 'Day') day_name,
	date_part('isodow' , date) day_of_week,
	date_part('day' , date) day_of_month,
	date_part('doy' , date) - date_part('doy' , DATE_TRUNC('quarter',date)) + 1 day_of_quarter,
	date_part('doy' , date) day_of_year,
	cast(to_char(date, 'W') as int) week_of_month,
	date_part('week' , date) week_of_year,
	to_char(date, 'YYYY-"W"WW-ID')  week_of_year_iso,
	date_part('month' , date) month_actual,
	to_char(date, 'Month') month_name,
	to_char(date, 'Mon') month_name_abbreviated,
	date_part('quarter' , date) quarter_actual,
	to_char(date, 'Qth') quarter_name,
	date_part('year' , date) year_actual,
	DATE_TRUNC('week',date)::date first_day_of_week,
	(DATE_TRUNC('week', date) + interval '1 week' - interval '1 day')::date last_day_of_week,
	DATE_TRUNC('month',date)::date first_day_of_month,
	(DATE_TRUNC('month', date) + interval '1 month' - interval '1 day')::date last_day_of_month,
	DATE_TRUNC('quarter',date)::date first_day_of_quarter,
	(DATE_TRUNC('quarter', date) + interval '3 month' - interval '1 day')::date last_day_of_quarter,
	DATE_TRUNC('year',date)::date first_day_of_year,
	(DATE_TRUNC('year', date) + interval '1 year' - interval '1 day')::date last_day_of_year,
	to_char(date, 'mmyyyy') mmyyyy,
	to_char(date, 'mmddyyyy') mmddyyyy,
	case when date_part('isodow' , date) in (6,7) then true else false end weekend_indr
from generate_series('1970-01-01'::timestamp, '2049-12-31', '1 day') as t(date);
